version: "2.1"

services:
  chsa-c1-00:
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c1-00
    image: chsaexercises/systemd-c1-00:1.0.8-xenial
    container_name: chsa-c1-00
    hostname: chsa-c1-00
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./assets/chsa-c1-00/validator.priv:/etc/sawtooth/keys/validator.priv:ro
      - ./assets/chsa-c1-00/validator.pub:/etc/sawtooth/keys/validator.pub:ro

  chsa-c1-01:
    depends_on:
      - chsa-c1-00
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c1-01
    image: chsaexercises/systemd-c1-01:1.0.8-xenial
    container_name: chsa-c1-01
    hostname: chsa-c1-01
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./assets/chsa-c1-01/validator.priv:/etc/sawtooth/keys/validator.priv:ro
      - ./assets/chsa-c1-01/validator.pub:/etc/sawtooth/keys/validator.pub:ro

  chsa-c1-02:
    depends_on:
      - chsa-c1-00
    privileged: true
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c1-02
    image: chsaexercises/systemd-c1-02:1.0.8-xenial
    container_name: chsa-c1-02
    hostname: chsa-c1-02
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./assets/chsa-c1-02/validator.priv:/etc/sawtooth/keys/validator.priv:ro
      - ./assets/chsa-c1-02/validator.pub:/etc/sawtooth/keys/validator.pub:ro

  chsa-c1-loadgen:
    privileged: true
    build: 
      context: ./
      dockerfile: Dockerfile.loadgen
      args:
        ASSET_PATH: assets/chsa-c1-loadgen
    image: chsaexercises/systemd-c1-loadgen:1.0.8-xenial
    container_name: chsa-c1-loadgen
    hostname: chsa-c1-loadgen
    volumes:
      - ./assets/loadgen.priv:/home/loadgen/.sawtooth/keys/loadgen.priv
      - ./assets/loadgen.pub:/home/loadgen/.sawtooth/keys/loadgen.pub
