version: "2.2"

services:
  chsa-c3-00:
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c3-00
    image: chsaexercises/systemd-c3-00:1.0.8-xenial
    container_name: chsa-c3-00
    hostname: chsa-c3-00
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./assets/sysops.priv:/home/sysops/.sawtooth/keys/sysops.priv
      - ./assets/sysops.pub:/home/sysops/.sawtooth/keys/sysops.pub

  chsa-c3-01:
    depends_on:
      - chsa-c3-00
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c3-01
    image: chsaexercises/systemd-c3-01:1.0.8-xenial
    container_name: chsa-c3-01
    hostname: chsa-c3-01
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./assets/sysops.priv:/home/sysops/.sawtooth/keys/sysops.priv
      - ./assets/sysops.pub:/home/sysops/.sawtooth/keys/sysops.pub

  chsa-c3-02:
    depends_on:
      - chsa-c3-00
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-c3-02
    image: chsaexercises/systemd-c3-02:1.0.8-xenial
    container_name: chsa-c3-02
    hostname: chsa-c3-02
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./assets/sysops.priv:/home/sysops/.sawtooth/keys/sysops.priv
      - ./assets/sysops.pub:/home/sysops/.sawtooth/keys/sysops.pub

  chsa-c3-loadgen:
    build: 
      context: ./
      dockerfile: Dockerfile.loadgen
      args:
        ASSET_PATH: assets/chsa-c3-loadgen
    image: chsaexercises/systemd-c3-loadgen:1.0.8-xenial
    container_name: chsa-c3-loadgen
    hostname: chsa-c3-loadgen
    volumes:
      - ./assets/loadgen.priv:/home/loadgen/.sawtooth/keys/loadgen.priv
      - ./assets/loadgen.pub:/home/loadgen/.sawtooth/keys/loadgen.pub
