env:
  - PATHWAY=cncftmb_ci-cd
  - PATHWAY=cncftme_service-proxy-discovery-mesh
  - PATHWAY=doe_continuous-delivery
  - PATHWAY=hsa_hyperledger-sawtooth-install
  - PATHWAY=hsb_hyperledger-sawtooth-configuration
  - PATHWAY=hsc_hyperledger-sawtooth-security
  
sudo: required
services:
  - docker

# before_install:
#   # Install Katacoda  CLI
#   - npm install -g katacoda-cli

script: >-
  for SCENARIO in $(cat ${PATHWAY}-pathway.json | jq -r .courses[].course_id); 
  do 
    pushd ${PATHWAY}/${SCENARIO}/assets/ && 
    docker-compose up -d --build
    popd
  done
after_success: >-
  echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin &&
  for SCENARIO in $(cat ${PATHWAY}-pathway.json | jq -r .courses[].course_id);
   do 
    pushd ${PATHWAY}/${SCENARIO}/assets/ && 
    docker-compose push
    popd
  done
