apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: argo
  namespace: argo
spec:
  rules:
  - http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            serviceName: argo-server
            servicePort: 2746