version: "2.1"

services:
  argo-tools:
    build: ./
    image: docker.io/cncfexercises/argo:latest
    container_name: argo-tools
    hostname: argo-tools
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro