  
version: "2.2"

services:
  chsa-a2-00:
    build: 
      context: ./
    image: chsaexercises/systemd-a2-00:1.0.8-xenial
    container_name: chsa-a2-00
    hostname: chsa-a2-00
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro