apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kiali
  namespace: istio-system
spec:
  rules:
  - http:
      paths:
        - path: "/kiali"
          backend:
            serviceName: kiali
            servicePort: 20001
