version: "2.1"

services:
  chsa-a4-00:
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-a4-00
    image: chsaexercises/systemd-a4-00:1.0.8-xenial
    container_name: chsa-a4-00
    hostname: chsa-a4-00
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  chsa-a4-01:
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-a4-01
    image: chsaexercises/systemd-a4-01:1.0.8-xenial
    container_name: chsa-a4-01
    hostname: chsa-a4-01
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  chsa-a4-02:
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-a4-02
    image: chsaexercises/systemd-a4-02:1.0.8-xenial
    container_name: chsa-a4-02
    hostname: chsa-a4-02
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
