version: "2.2"

services:
  chsa-a9-00:
    build: 
      context: ./
      args:
        ASSET_PATH: assets/chsa-a9-00
    image: chsaexercises/systemd-a9-00:1.0.8-xenial
    container_name: chsa-a9-00
    hostname: chsa-a9-00
    expose:
      - 8800
      - 4004
      - 8008
    security_opt:
      - seccomp:unconfined
    tty: true
    user: root
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
